variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - release

.check:
  stage: test
  image: cr.yandex/crpoem3mqq83iobvune7/hse-cxx-testenv:latest
  allow_failure: true
  script:
    - cmake --version
    - mkdir -p build/solutions
    - cd build/solutions
    - cmake ../../ -G Ninja -DTEST_SOLUTION=ON -DENABLE_PRIVATE_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - ninja test-all

check-solutions-gcc-10-debug:
  extends: .check
  variables:
    CC: gcc-10
    CXX: g++-10
    BUILD_TYPE: Debug

check-solutions-clang-11-debug:
  extends: .check
  variables:
    CC: clang-11
    CXX: clang++-11
    BUILD_TYPE: Debug

check-solutions-clang-11-asan:
  extends: .check
  variables:
    CC: clang-11
    CXX: clang++-11
    BUILD_TYPE: ASAN

deploy:
  only:
  - main
  tags:
  - docker
  stage: release
  script:
  - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - source ~/.bashrc
  - yc container registry configure-docker
  - docker pull cr.yandex/crpoem3mqq83iobvune7/hse-cxx-build:latest
  - git checkout .
  - docker build -f testenv.docker -t cr.yandex/crpoem3mqq83iobvune7/hse-cxx-testenv .
  - docker push cr.yandex/crpoem3mqq83iobvune7/hse-cxx-testenv:latest
