grade:
  image: cr.yandex/crpi3u88u344uak6pq2t/hse-cxx-testenv:latest
  only:
    - /^submits/.*$/
  script:
    - cd /opt/shad && PYTHONPATH=grader python3 -m grader
  artifacts:
    when: on_failure
    paths:
      - artifacts/
